name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests

      - name: Start FastAPI server
        run: |
          nohup uvicorn apiserver:app --host 0.0.0.0 --port 8000 &  # Start FastAPI in the background
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server to be ready
        run: |
          for i in $(seq 1 10); do
            if curl --silent --fail http://localhost:8000 > /dev/null; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 5
            fi
          done

      - name: Run tests
        run: |
          pytest testAutomation.py  # Use the correct relative path
